services:
  app:
    build: .
    volumes:
      - .:/app
      - ./input:/app/input
      - ./output:/app/output
    working_dir: /app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    dns:
      - 8.8.8.8
      - 8.8.4.4